import React, { useState } from 'react';
import { type TimeBlock, BlockStatus } from '../types';
import { Play, Check, Clock, Calendar as CalendarIcon, Loader2, Sparkles } from 'lucide-react';
import { format, parseISO } from 'date-fns';

interface DailyScheduleProps {
    blocks: TimeBlock[];
    onCompleteBlock: (block: TimeBlock) => void;
    onGenerate: (hours: number) => Promise<void>;
    isLoading: boolean;
}

const DailySchedule: React.FC<DailyScheduleProps> = ({ blocks, onCompleteBlock, onGenerate, isLoading }) => {
    const [availableHours, setAvailableHours] = useState<number>(8);

    const handleGenerate = () => {
        onGenerate(availableHours);
    };

    const renderBlock = (block: TimeBlock) => {
        const isAI = block.source === 'system' && !block.is_fixed;
        const isFixed = block.is_fixed;
        const isAllDay = block.is_all_day;
        const isSurprise = isAI && !block.task_id; // Surprise tasks generated by AI don't have a task_id initially

        let borderColor = 'border-slate-200';
        let bgColor = 'bg-white';
        let icon = <Clock className="w-4 h-4 text-slate-400" />;

        if (isFixed) {
            borderColor = 'border-red-200';
            bgColor = 'bg-red-50/50';
            icon = <CalendarIcon className="w-4 h-4 text-red-500" />;
        } else if (isSurprise) {
            borderColor = 'border-purple-200';
            bgColor = 'bg-purple-50/50';
            icon = <Sparkles className="w-4 h-4 text-purple-500" />;
        } else if (isAI) {
            borderColor = 'border-blue-200';
            bgColor = 'bg-blue-50/30';
            icon = <Play className="w-4 h-4 text-blue-500" />;
        }

        const timeString = block.start_time 
            ? `${format(parseISO(block.start_time), 'HH:mm')} (${block.duration_hours}h)`
            : `${block.duration_hours}h Flexible`;

        return (
            <div key={block.id} className={`p-4 rounded-xl border ${borderColor} ${bgColor} shadow-sm mb-3 flex items-start gap-4 transition-all hover:shadow-md`}>
                <div className="mt-1">
                    {icon}
                </div>
                <div className="flex-1">
                    <div className="flex justify-between items-start">
                        <h4 className={`font-bold text-slate-800 ${block.status === BlockStatus.COMPLETED ? 'line-through opacity-60' : ''}`}>
                            {block.title}
                        </h4>
                        {!isFixed && !isAllDay && block.status !== BlockStatus.COMPLETED && (
                            <button 
                                onClick={() => onCompleteBlock(block)}
                                className="bg-emerald-50 text-emerald-600 hover:bg-emerald-100 text-[11px] font-bold uppercase px-3 py-1.5 rounded-lg transition-all flex items-center gap-1"
                            >
                                <Check className="w-3 h-3" /> Complete
                            </button>
                        )}
                        {block.status === BlockStatus.COMPLETED && (
                            <span className="text-[11px] font-bold uppercase text-emerald-500 flex items-center gap-1">
                                <Check className="w-3 h-3" /> Done
                            </span>
                        )}
                    </div>
                    {!isAllDay && (
                        <div className="text-sm font-medium text-slate-500 mt-1 flex items-center gap-2">
                            <span>{timeString}</span>
                            {isSurprise && <span className="bg-purple-100 text-purple-700 px-2 py-0.5 rounded text-[10px] uppercase tracking-wider">AI Suggestion</span>}
                            {isFixed && <span className="bg-red-100 text-red-700 px-2 py-0.5 rounded text-[10px] uppercase tracking-wider">Fixed</span>}
                        </div>
                    )}
                </div>
            </div>
        );
    };

    const allDayEvents = blocks.filter(b => b.is_all_day);
    const scheduledBlocks = blocks.filter(b => !b.is_all_day).sort((a, b) => {
        if (!a.start_time) return 1;
        if (!b.start_time) return -1;
        return a.start_time.localeCompare(b.start_time);
    });

    return (
        <div className="max-w-3xl mx-auto">
            {allDayEvents.length > 0 && (
                <div className="mb-6 p-4 bg-amber-50 border border-amber-200 rounded-2xl shadow-sm">
                    <h3 className="text-amber-800 font-bold mb-2 flex items-center gap-2">
                        <Sparkles className="w-5 h-5" /> Today's Special Events
                    </h3>
                    <ul className="list-disc list-inside ml-5 text-amber-700 text-sm">
                        {allDayEvents.map(e => (
                            <li key={e.id}>{e.title}</li>
                        ))}
                    </ul>
                </div>
            )}

            <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm mb-8 flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
                        Project Manager
                    </h2>
                    <p className="text-slate-500 text-sm mt-1">Let AI dynamically pack your day based on your flexible tasks and fixed meetings.</p>
                </div>
                <div className="flex items-center gap-3">
                    <div className="flex flex-col">
                        <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Available Hours</label>
                        <input 
                            type="number" 
                            min="1" max="24" step="0.5"
                            value={availableHours}
                            onChange={(e) => setAvailableHours(Number(e.target.value))}
                            className="w-20 bg-slate-50 border border-slate-200 rounded-lg px-3 py-1.5 text-sm text-slate-700 focus:outline-none focus:border-blue-500 transition-all text-center"
                        />
                    </div>
                    <button 
                        onClick={handleGenerate}
                        disabled={isLoading}
                        className="mt-4 bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-xl font-bold transition-all shadow-md shadow-blue-500/20 flex items-center gap-2 disabled:opacity-50"
                    >
                        {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                        Plan My Day
                    </button>
                </div>
            </div>

            <div className="space-y-1">
                {scheduledBlocks.length === 0 ? (
                    <div className="text-center py-20 bg-white rounded-2xl border-2 border-dashed border-slate-200">
                        <div className="bg-slate-50 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                            <CalendarIcon className="w-8 h-8 text-slate-300" />
                        </div>
                        <p className="text-slate-500 font-medium">Your schedule is empty.</p>
                        <p className="text-slate-400 text-sm mt-1">Click "Plan My Day" to let AI schedule your tasks.</p>
                    </div>
                ) : (
                    scheduledBlocks.map(renderBlock)
                )}
            </div>
        </div>
    );
};

export default DailySchedule;
